name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Check Backend
    - name: Install Server Dependencies
      run: |
        cd server
        npm install

    # Check Frontend
    - name: Install Client Dependencies
      run: |
        cd client
        npm install
        npm run build # This checks if your React code has errors